/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpls.online.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author wflores
 */
@Template(CrudFormPage.class)
public class OnlineBusinessApplicationPage extends javax.swing.JPanel {

    /**
     * Creates new form OnlineBusinessApplicationPage
     */
    public OnlineBusinessApplicationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xTabbedPane1 = new com.rameses.rcp.control.XTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel3 = new javax.swing.JPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();
        jPanel8 = new javax.swing.JPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        xLabel19 = new com.rameses.rcp.control.XLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setPreferredSize(new java.awt.Dimension(820, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.XLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(30, 15, 20, 15));
        xTitledBorder1.setTitle("   General Information    ");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(110);
        xFormPanel1.setPreferredSize(new java.awt.Dimension(500, 195));

        xLabel1.setCaption("BIN");
        xLabel1.setExpression("#{entity.bin}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setHideLeft(true);
        xLineBorder1.setHideRight(true);
        xLineBorder1.setHideTop(true);
        xLineBorder1.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel1.setBorder(xLineBorder1);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel1.setStretchWidth(100);
        xFormPanel1.add(xLabel1);

        xLabel3.setCaption("Trade Name");
        xLabel3.setExpression("#{entity.tradename}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder2 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder2.setHideLeft(true);
        xLineBorder2.setHideRight(true);
        xLineBorder2.setHideTop(true);
        xLineBorder2.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel3.setBorder(xLineBorder2);
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel3.setStretchWidth(100);
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Business Name");
        xLabel4.setExpression("#{entity.businessname}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder3 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder3.setHideLeft(true);
        xLineBorder3.setHideRight(true);
        xLineBorder3.setHideTop(true);
        xLineBorder3.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel4.setBorder(xLineBorder3);
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel4.setStretchWidth(100);
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Business Address");
        xLabel5.setExpression("#{entity.address.text}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder4 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder4.setHideLeft(true);
        xLineBorder4.setHideRight(true);
        xLineBorder4.setHideTop(true);
        xLineBorder4.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel5.setBorder(xLineBorder4);
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel5.setStretchWidth(100);
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Owner Name");
        xLabel6.setExpression("#{entity.owner.name}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder5 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder5.setHideLeft(true);
        xLineBorder5.setHideRight(true);
        xLineBorder5.setHideTop(true);
        xLineBorder5.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel6.setBorder(xLineBorder5);
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel6.setStretchWidth(100);
        xFormPanel1.add(xLabel6);

        xLabel7.setCaption("Owner Address");
        xLabel7.setExpression("#{entity.owner.address.text}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder6 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder6.setHideLeft(true);
        xLineBorder6.setHideRight(true);
        xLineBorder6.setHideTop(true);
        xLineBorder6.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel7.setBorder(xLineBorder6);
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel7.setStretchWidth(100);
        xFormPanel1.add(xLabel7);

        xLabel13.setCaption("Org. Type");
        xLabel13.setExpression("#{entity.orgtype}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder7 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder7.setHideLeft(true);
        xLineBorder7.setHideRight(true);
        xLineBorder7.setHideTop(true);
        xLineBorder7.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel13.setBorder(xLineBorder7);
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel13.setStretchWidth(100);
        xFormPanel1.add(xLabel13);

        jPanel1.add(xFormPanel1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setPadding(new java.awt.Insets(30, 15, 20, 15));
        xTitledBorder2.setTitle("   Application Information    ");
        xFormPanel2.setBorder(xTitledBorder2);
        xFormPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel2.setCaptionWidth(100);
        xFormPanel2.setPreferredSize(new java.awt.Dimension(300, 160));

        xLabel2.setCaption("Control No");
        xLabel2.setExpression("#{entity.controlno}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder8 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder8.setHideLeft(true);
        xLineBorder8.setHideRight(true);
        xLineBorder8.setHideTop(true);
        xLineBorder8.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel2.setBorder(xLineBorder8);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel2.setStretchWidth(100);
        xFormPanel2.add(xLabel2);

        xLabel11.setCaption("Date Created");
        xLabel11.setExpression("#{entity.dtcreated}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder9 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder9.setHideLeft(true);
        xLineBorder9.setHideRight(true);
        xLineBorder9.setHideTop(true);
        xLineBorder9.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel11.setBorder(xLineBorder9);
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel11.setStretchWidth(100);
        xFormPanel2.add(xLabel11);

        xLabel8.setCaption("App. Date");
        xLabel8.setExpression("#{entity.appdate}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder10 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder10.setHideLeft(true);
        xLineBorder10.setHideRight(true);
        xLineBorder10.setHideTop(true);
        xLineBorder10.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel8.setBorder(xLineBorder10);
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel8.setStretchWidth(100);
        xFormPanel2.add(xLabel8);

        xLabel9.setCaption("App. Type");
        xLabel9.setExpression("#{entity.apptype}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder11 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder11.setHideLeft(true);
        xLineBorder11.setHideRight(true);
        xLineBorder11.setHideTop(true);
        xLineBorder11.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel9.setBorder(xLineBorder11);
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel9.setStretchWidth(100);
        xFormPanel2.add(xLabel9);

        xLabel10.setCaption("App. Year");
        xLabel10.setExpression("#{entity.appyear}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder12 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder12.setHideLeft(true);
        xLineBorder12.setHideRight(true);
        xLineBorder12.setHideTop(true);
        xLineBorder12.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel10.setBorder(xLineBorder12);
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel10.setStretchWidth(100);
        xFormPanel2.add(xLabel10);

        xLabel12.setCaption("Status");
        xLabel12.setExpression("#{entity.state}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder13 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder13.setHideLeft(true);
        xLineBorder13.setHideRight(true);
        xLineBorder13.setHideTop(true);
        xLineBorder13.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel12.setBorder(xLineBorder13);
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel12.setStretchWidth(100);
        xFormPanel2.add(xLabel12);

        jPanel1.add(xFormPanel2);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        xDataTable1.setHandler("lobListHandler");
        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "lob.name"}
                , new Object[]{"caption", "Name"}
                , new Object[]{"width", 200}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "prevgross"}
                , new Object[]{"caption", "Previous Gross"}
                , new Object[]{"width", 120}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 120}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "gross"}
                , new Object[]{"caption", "Gross"}
                , new Object[]{"width", 120}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 120}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "assessmenttype"}
                , new Object[]{"caption", "Assessment Type"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable1.setDynamic(true);
        jPanel2.add(xDataTable1, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("   Line of Business      ", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        xDataTable2.setHandler("infoListHandler");
        xDataTable2.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "caption"}
                , new Object[]{"caption", "Attribute"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"alignment", "LEFT"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "value"}
                , new Object[]{"caption", "Value"}
                , new Object[]{"width", 120}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 120}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "filler"}
                , new Object[]{"caption", " "}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable2.setDynamic(true);
        jPanel3.add(xDataTable2, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("   Business Infos      ", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 0));
        com.rameses.rcp.control.layout.XLayout xLayout2 = new com.rameses.rcp.control.layout.XLayout();
        xLayout2.setSpacing(5);
        jPanel5.setLayout(xLayout2);

        xButton1.setDepends(new String[] {"selectedRequirement"});
        xButton1.setDisableWhen("#{withAttachment == false}");
        xButton1.setName("downloadAttachment"); // NOI18N
        xButton1.setText("Download Attachment");
        jPanel5.add(xButton1);

        xButton2.setDepends(new String[] {"selectedRequirement"});
        xButton2.setDisableWhen("#{withAttachment == false}");
        xButton2.setName("viewAttachment"); // NOI18N
        xButton2.setText("View Attachment");
        jPanel5.add(xButton2);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        xDataTable3.setHandler("requirementListHandler");
        xDataTable3.setName("selectedRequirement"); // NOI18N
        xDataTable3.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "caption"}
                , new Object[]{"caption", "Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"alignment", "LEFT"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "hasattachment"}
                , new Object[]{"caption", "Has Attachment?"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 100}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.CheckBoxColumnHandler(java.lang.Boolean.class, true, false)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "refno"}
                , new Object[]{"caption", "RefNo"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 100}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "dtissued"}
                , new Object[]{"caption", "Date Issued"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 100}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "placeissued"}
                , new Object[]{"caption", "Place Issued"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable3.setDynamic(true);
        jPanel4.add(xDataTable3, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("   Requirements       ", jPanel4);

        xFormPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 0));
        xFormPanel3.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel3.setCaptionWidth(110);
        xFormPanel3.setPreferredSize(new java.awt.Dimension(805, 110));

        xLabel14.setCaption("Name");
        xLabel14.setExpression("#{entity.contact.name}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder14 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder14.setHideLeft(true);
        xLineBorder14.setHideRight(true);
        xLineBorder14.setHideTop(true);
        xLineBorder14.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel14.setBorder(xLineBorder14);
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel14.setStretchWidth(100);
        xFormPanel3.add(xLabel14);

        xLabel17.setCaption("Address");
        xLabel17.setExpression("#{entity.contact.address ? entity.contact.address.replace('\\\\n',' ') : ' '}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder15 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder15.setHideLeft(true);
        xLineBorder15.setHideRight(true);
        xLineBorder15.setHideTop(true);
        xLineBorder15.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel17.setBorder(xLineBorder15);
        xLabel17.setCellPadding(new java.awt.Insets(0, 0, 5, 0));
        xLabel17.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel17.setStretchWidth(100);
        xFormPanel3.add(xLabel17);

        xLabel18.setCaption("Email");
        xLabel18.setExpression("#{entity.contact.email}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder16 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder16.setHideLeft(true);
        xLineBorder16.setHideRight(true);
        xLineBorder16.setHideTop(true);
        xLineBorder16.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel18.setBorder(xLineBorder16);
        xLabel18.setPreferredSize(new java.awt.Dimension(200, 20));
        xLabel18.setStretchWidth(100);
        xFormPanel3.add(xLabel18);

        xLabel19.setCaption("Mobile No.");
        xLabel19.setExpression("#{entity.contact.mobileno}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder17 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder17.setHideLeft(true);
        xLineBorder17.setHideRight(true);
        xLineBorder17.setHideTop(true);
        xLineBorder17.setLineColor(new java.awt.Color(180, 180, 180));
        xLabel19.setBorder(xLineBorder17);
        xLabel19.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel3.add(xLabel19);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        xTabbedPane1.addTab("   Contact Information     ", jPanel8);

        add(xTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel19;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XTabbedPane xTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
